platform :ios, '9.0'

use_frameworks!

target 'FutureMind' do
	pod 'Alamofire', '~> 4.7'
	pod 'ObjectMapper', '~> 3.2'
	pod 'RxSwift',    '~> 4.0'
    	pod 'RxCocoa',    '~> 4.0'
	pod 'Swinject', '~> 1.1.4'
end
